import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <div className={styles.container}>
      <Head>
        <title>devter 🐻‍❄️ </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className={styles.title}>
          <a className={styles.a} href="https://nextjs.org">
            devter
          </a>
        </h1>
        <nav className={styles.nav}>
          <a className={styles.a} href="/timeline">
            timeline
          </a>
        </nav>
      </main>
    </div>
  );
}
